#!/usr/bin/env python3
'''
Python script for Sysalytics.
This script pulls the following statistics.
- Battery percentage
- Is charging
- Governor
- CPU frequency
- Swappiness
- Power Profile
'''

import tools.firebase_conn as fb
import data.model as model

# Get document reference
dbRef = fb.send_doc_reference(".env")

# Write to JSON
dbRef.set(model.get_system_profile())